# Generated by Django 2.0.3 on 2018-04-07 04:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledinfodelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleInforDeliver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(max_length=50)),
                ('job_info_content', models.TextField()),
                ('day', models.IntegerField(blank=True, null=True)),
                ('hour', models.IntegerField(blank=True, null=True)),
                ('minute', models.IntegerField(blank=True, null=True)),
                ('second', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduledinfodelivery.User')),
            ],
        ),
    ]
