# Generated by Django 2.0.3 on 2018-04-07 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduledinfodelivery', '0002_scheduleinfordeliver'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleinfordeliver',
            name='job_status',
            field=models.CharField(default='idle', max_length=50),
        ),
    ]
